/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CommunityLink = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'iconType' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'totalRevenue' : IDL.Text,
  'newApplications' : IDL.Nat,
  'reportsCount' : IDL.Nat,
  'payoutNote' : IDL.Text,
  'applicationsTrend' : IDL.Text,
});
export const ModerationCounts = IDL.Record({
  'flaggedComments' : IDL.Nat,
  'pendingReviews' : IDL.Nat,
});
export const PaymentInfo = IDL.Record({
  'status' : IDL.Text,
  'bankName' : IDL.Text,
  'lastFour' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCommunityLink' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCommunityLink' : IDL.Func([IDL.Nat], [], []),
  'editCommunityLink' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllCommunityLinks' : IDL.Func([], [IDL.Vec(CommunityLink)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getModerationCounts' : IDL.Func([], [ModerationCounts], ['query']),
  'getPaymentInfo' : IDL.Func([], [PaymentInfo], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateDashboardStats' : IDL.Func([DashboardStats], [], []),
  'updateModerationCounts' : IDL.Func([ModerationCounts], [], []),
  'updatePaymentInfo' : IDL.Func([PaymentInfo], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CommunityLink = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'iconType' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'totalRevenue' : IDL.Text,
    'newApplications' : IDL.Nat,
    'reportsCount' : IDL.Nat,
    'payoutNote' : IDL.Text,
    'applicationsTrend' : IDL.Text,
  });
  const ModerationCounts = IDL.Record({
    'flaggedComments' : IDL.Nat,
    'pendingReviews' : IDL.Nat,
  });
  const PaymentInfo = IDL.Record({
    'status' : IDL.Text,
    'bankName' : IDL.Text,
    'lastFour' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCommunityLink' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCommunityLink' : IDL.Func([IDL.Nat], [], []),
    'editCommunityLink' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllCommunityLinks' : IDL.Func([], [IDL.Vec(CommunityLink)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getModerationCounts' : IDL.Func([], [ModerationCounts], ['query']),
    'getPaymentInfo' : IDL.Func([], [PaymentInfo], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateDashboardStats' : IDL.Func([DashboardStats], [], []),
    'updateModerationCounts' : IDL.Func([ModerationCounts], [], []),
    'updatePaymentInfo' : IDL.Func([PaymentInfo], [], []),
  });
};

export const init = ({ IDL }) => { return []; };